### PR TITLE
Update Malum, Mythic Metals and Powah support

### PR DESCRIPTION
**Pull request by ghost**
Quick note: Malum adds 'Brilliant Stone' and 'Brilliant Deepslate', I don't think there's a way to format the `en_name` to allow strings like 'Brilliant Andesite' so I just set it to be '\<stone> of Brilliance' as a workaround.

### CODE REVIEW

**Comment by lukebemish** [comment]
Good to know about the en_name thing; I'll probably end up switching that around to something regex based or the like eventually. Thanks!

**Comment by lukebemish** [comment]
(Waiting to merge as I'm going to implement something for the names; will probably be merged prior to the next release)

**Comment by lukebemish** [comment]
Merged; also changed some stuff in code to allow "Brilliant Andesite"

**Comment by ChromamoonMC** [comment]
On 1.20.1, Brilliant and Blazing Quartz Ore generate broken textures. While it is not as true to the mod, perhaps something like this would work better: 


```js
{
    mod_id: 'malum',
    provided_stones: [
    ],
    provided_ores: [
        {
            id: 'malum_brilliant_ore',
            stone: [
                'stone',
                'deepslate',
            ],
            block_id: [
                'malum:brilliant_stone',
                'malum:brilliant_deepslate',
            ],
            lang: {
                en_us: 'Brilliant Ore',
            },
            types: [
                'stone',
            ],
        },
        {
            id: 'malum_cthonic_gold_ore',
            stone: [
                'deepslate',
            ],
            block_id: [
                'malum:cthonic_gold_ore',
            ],
            lang: {
                en_us: 'Cthonic Gold Ore',
            },
            types: [
                'stone',
            ],
        },
        {
            id: 'malum_quartz_ore',
            stone: [
                'stone',
                'deepslate',
            ],
            block_id: [
                'malum:natural_quartz_ore',
                'malum:deepslate_quartz_ore',
            ],
            lang: {
                en_us: 'Quartz Ore',
            },
            types: [
                'stone',
            ],
        },
        {
            id: 'malum_soulstone_ore',
            stone: [
                'stone',
                'deepslate',
            ],
            block_id: [
                'malum:soulstone_ore',
                'malum:deepslate_soulstone_ore',
            ],
            lang: {
                en_us: 'Soulstone Ore',
            },
            types: [
                'stone',
            ],
        },
        {
            id: 'malum_blazing_quartz_ore',
            stone: [
                'netherrack',
            ],
            block_id: [
                'malum:blazing_quartz_ore',
            ],
            lang: {
                en_us: 'Blazing Quartz Ore',
            },
            types: [
                'nether',
            ],
        },
    ],
}
```

**Pull request merged**
