### PR TITLE
Create magnificent_malachite

### PR DESCRIPTION
**Pull request by cowsha**

### CODE REVIEW

**Comment by cowsha** [comment]
Was fun to make. This tool is pure magic, they look so natural.

**Comment by lukebemish** [comment]
I'll merge this once I've got the code ready for the next release; currently, I've got some major internal changes going on. Shouldn't affect the config structure, though.

**Comment by cowsha** [comment]
Cool, thanks for amazing mod!
Gotta make another one for sulfur and potassium mod.

**Review by lukebemish — CHANGES_REQUESTED** [review]
This file appears to not have an extension.

**Review by lukebemish — APPROVED** [review]

**Pull request merged**
