### PR TITLE
Default Config Additions: ms.json5 (for the Mo' Shiz mod) and crystalcraft_unlimited_java.json5 configs for Minecraft 1.19.4

### PR DESCRIPTION
**Pull request by ChromamoonMC**
This is the config for the Mo' Shiz mod for Minecraft 1.19.4.

### CODE REVIEW

**Comment by ChromamoonMC** [comment]
I also just added the file for the CrystalCraft Unlimited Java Edition mod. Both JSON5 files have been tested and work successfully on my end.

**Comment by ChromamoonMC** [comment]
@lukebemish could you please review this when you get a chance? Thanks.

**Comment by lukebemish** [comment]
So sorry, I've been rather busy with exams lately; I'll poke this in the next few weeks.

**Comment by lukebemish** [comment]
After considering this further, I will not be merging it -- it looks great, but I am not actively developing the 1.19.4 version, and in fact as I discovered getting publishing working for it again would take some work when I have no intention of releasing future versions. Feel free to distribute the configs you've made separately!

**Comment by Lcs128** [comment]
@lukebemish  the creator of crystalcraft here, crystalcraft unlimited is now also for 1.20.4 and 1.20.6, could you reconsider adding the configs. Here are the updated configs for 1.20.4+ (I am not 100% sure if I did it correctly though)
[Crystalcraft_Unlimited_Java.zip](https://github.com/user-attachments/files/16601923/Crystalcraft_Unlimited_Java.zip)

**Comment by lukebemish** [comment]
Thank you; I'll look into it once I have a chance

**Pull request closed without merging**
