### PR TITLE
Support a bunch more Fabric/Quilt mods and improve Mythic Metals support

### PR DESCRIPTION
**Pull request by ghost**
Some of the mods are not that popular, but I added support for them in my modpack anyway so I've decided to commit them here.

Let me know if:
* You don't want to have to maintain support for some of these mods
* If I should pull request to the 1.19 thread instead, my pack is 1.18 and not all of these mods have updated

### CODE REVIEW

**Comment by lukebemish** [comment]
I have a few questions:
- What exactly was changed in the MI config? Why does it involve rewriting the whole file?
- There's some inconsistent indentation. Please fix it.
- Same issues with the mythic metals changes; there seem to be a lot of format/ordering changes within the configs, which makes it hard to tell what actually changed.
- The default texture_count is now 10; could you please update your changes accordingly? Or just remove the field, as it's optional (this is the preferred option, as it supports future changes to this default)
Otherwise, this looks great. Thank you!

**Comment by goldenapple3** [comment]
Sorry for not responding earlier:
* I think I originally wrote the MI config before that was added to the base repo, looks like it's not needed now.
* Will fix.
* Mythic Metals config had been completely rewritten as it was missing a lot of ores.
* I honestly don't know what the texture_count field actually does so I will just remove it.

**Comment by goldenapple3** [comment]
I think the one tiny difference is in my config I set the MI Lighnite Coal Ore to have the same ID as the Biomes You'll Go Lignite Ore, they are practically the same thing though they do not share item tags. But for now I'll just pull your version.

**Comment by lukebemish** [comment]
Still not sure why the mythic metals config was rewritten instead of changing/adding to the existing one, but it looks good enough. Merging into the next update for 1.19, and into the last bugfix update for 1.18.

**Pull request merged**
