### PR TITLE
Added default config for FTB:IC

### PR DESCRIPTION
**Pull request by DMNerd**
FTB industrial contraptions ores

### CODE REVIEW

**Comment by lukebemish** [comment]
Have you tested this locally? FTB IC does some weirdness with their models meaning that this can't currently find the models correctly. It's something I'm working on.

**Comment by DMNerd** [comment]
I am currently testing this. I will report later

**Comment by lukebemish** [comment]
I already know it will not work; I'm working on a way around it now. However, I do appreciate it when people test configs before PRing them.

**Comment by lukebemish** [comment]
Changed some stuff around to get composite model types working; in theory, this will work fine in the next 1.19 version.

**Comment by DMNerd** [comment]
Thank you

**Pull request merged**
