### PR TITLE
Create biomesofplenty.json

### PR DESCRIPTION
**Pull request by ZEROX7**
support for biomesofplenty sandstones

### CODE REVIEW

**Comment by lukebemish** [comment]
Please fix whatever is up with the limestone entry; then I'll merge this

**Comment by ZEROX7** [comment]
done

**Comment by lukebemish** [comment]
Can you switch everything to proper (space-based) and consistent indentation? Otherwise, I'll merge this into the next release.

**Comment by ZEROX7** [comment]
done

**Pull request merged**
