### PR TITLE
added some ore

### PR DESCRIPTION
**Pull request by ardissaps**
my first pr on github ever

### CODE REVIEW

**Comment by lukebemish** [comment]
Was this PR supposed to do something?

**Comment by ardissaps** [comment]
> Was this PR supposed to do something?

Once upon a time I exploring and found Banglum ore with gray stone background spawn in the middle of orange stone (i didn't remember what stone). I figured out that some ores from MythicMetal not configured yet so I edit and add the missing ores (Morkite, Kyber, Aquarium ore etc).

**Comment by lukebemish** [comment]
Yes; however, you closed your own PR

**Comment by ardissaps** [comment]
> Yes; however, you closed your own PR

Is it? This my my first pr, look I have no clue which button to press, how to open?

**Comment by lukebemish** [comment]
Press "reopen" or something like that

**Review by ardissaps — COMMENTED** [review]
Test

**Comment by lukebemish** [comment]
You need to reopen the PR before you can do anything

**Pull request closed without merging**
