### PR TITLE
Backport Gems & Jewels + Galosphere + Darker Depths config to 1.18.2

### PR DESCRIPTION
**Pull request by Numerosityy**
The Gems & Jewels config could be ported to future versions as well

### CODE REVIEW

**Comment by lukebemish** [comment]
For the sake of convention, can we remove "block" from the `en_name` entries for "Gems and Jewels"?

**Comment by lukebemish** [comment]
Additionally, you seem to have both tabs and spaces in places. Could you switch everything to spaces?

**Comment by Numerosityy** [comment]
Yes, I had it originally because that's how Gems & Jewels blocks were named, although I prefer it without the word block. Both issues should be fixed now

**Comment by Numerosityy** [comment]
By the way, if there are any other interesting mods that you or community members think deserve compatibility, I'd be glad to add it

**Pull request merged**
