### PR TITLE
Update mythicmetals.json

### PR DESCRIPTION
**Pull request by ardissaps**

### CODE REVIEW

**Comment by lukebemish** [comment]
There seem to be a lot of format/ordering changes within the configs, which makes it hard to tell what actually changed. Is there any reason for this? Can it be avoided? Additionally, please avoid adding the `texture_count` parameter to configs. It is meant to be optional, and should be missing by default in all configs unless necessary.

**Comment by ardissaps** [comment]
I just copied file from my minecraft folder edit. Sorry if not good, I just trying help while learning.  Please ignore if the result is bad.  I'll try again later.

**Comment by lukebemish** [comment]
You can just edit the file on the fork you've already got. Please try editing the original file in default_configs, and keeping to that format, if possible.

**Comment by ardissaps** [comment]
Alright, my bad.

**Pull request closed without merging**
